-- 코드를 입력하세요

SELECT D.MCDP_CD AS 진료과코드, COUNT(*) AS 5월예약건수
FROM (SELECT MCDP_CD
      FROM APPOINTMENT
      WHERE YEAR(APNT_YMD)="2022" AND MONTH(APNT_YMD)="5") AS D
GROUP BY D.MCDP_cD
ORDER BY 5월예약건수, 진료과코드

