

SELECT I.ID, N.FISH_NAME, I.LENGTH
  FROM FISH_INFO I
  JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
 WHERE (I.FISH_TYPE, I.LENGTH) IN (
    # 집계 먼저 -> ID를 가져오기 위한 WHERE절
    SELECT FISH_TYPE, MAX(LENGTH)
      FROM FISH_INFO
     GROUP BY FISH_TYPE
 )
 ORDER BY I.ID;